// Code generated by ogen, DO NOT EDIT.

package ogen

import (
	"github.com/go-faster/errors"
)

func (s ListDailyMealsOKApplicationJSON) Validate() error {
	alias := ([]Meal)(s)
	if alias == nil {
		return errors.New("nil is invalid value")
	}
	return nil
}
