// Code generated by ogen, DO NOT EDIT.

package ogen

// OperationName is the ogen operation name
type OperationName = string

const (
	CreateDailyMealOperation OperationName = "CreateDailyMeal"
	GetDailyMealOperation    OperationName = "GetDailyMeal"
	ListDailyMealsOperation  OperationName = "ListDailyMeals"
)
