// Code generated by ogen, DO NOT EDIT.
package ogen

type CreateDailyMealRes interface {
	createDailyMealRes()
}

type GetDailyMealRes interface {
	getDailyMealRes()
}

type ListDailyMealsRes interface {
	listDailyMealsRes()
}
