// Code generated by ogen, DO NOT EDIT.

package ogen

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// CreateDailyMeal implements createDailyMeal operation.
	//
	// Добавляет продукт на основе переданного JSON-объекта.
	//
	// POST /daily-meal
	CreateDailyMeal(ctx context.Context, req *CreateDailyMealRequest) (CreateDailyMealRes, error)
	// GetDailyMeal implements getDailyMeal operation.
	//
	// Получить продукт по выбранному id.
	//
	// GET /daily-meal/{mealId}
	GetDailyMeal(ctx context.Context, params GetDailyMealParams) (GetDailyMealRes, error)
	// ListDailyMeals implements listDailyMeals operation.
	//
	// Возвращает массив продуктов, которые были добавлены.
	//
	// GET /daily-meal
	ListDailyMeals(ctx context.Context) (ListDailyMealsRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
