// Code generated by ogen, DO NOT EDIT.

package ogen

import (
	"net/http"
	"net/url"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

// GetDailyMealParams is parameters of getDailyMeal operation.
type GetDailyMealParams struct {
	// Meal identifier.
	MealId int64
}

func unpackGetDailyMealParams(packed middleware.Parameters) (params GetDailyMealParams) {
	{
		key := middleware.ParameterKey{
			Name: "mealId",
			In:   "path",
		}
		params.MealId = packed[key].(int64)
	}
	return params
}

func decodeGetDailyMealParams(args [1]string, argsEscaped bool, r *http.Request) (params GetDailyMealParams, _ error) {
	// Decode path: mealId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "mealId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToInt64(val)
				if err != nil {
					return err
				}

				params.MealId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "mealId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}
