// Code generated by ogen, DO NOT EDIT.

package ogen

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// CreateDailyMeal implements createDailyMeal operation.
//
// Добавляет продукт на основе переданного JSON-объекта.
//
// POST /daily-meal
func (UnimplementedHandler) CreateDailyMeal(ctx context.Context, req *CreateDailyMealRequest) (r CreateDailyMealRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetDailyMeal implements getDailyMeal operation.
//
// Получить продукт по выбранному id.
//
// GET /daily-meal/{mealId}
func (UnimplementedHandler) GetDailyMeal(ctx context.Context, params GetDailyMealParams) (r GetDailyMealRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListDailyMeals implements listDailyMeals operation.
//
// Возвращает массив продуктов, которые были добавлены.
//
// GET /daily-meal
func (UnimplementedHandler) ListDailyMeals(ctx context.Context) (r ListDailyMealsRes, _ error) {
	return r, ht.ErrNotImplemented
}
