// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: meals.sql

package sqlc

import (
	"context"
)

const createDailyMeal = `-- name: CreateDailyMeal :one
INSERT INTO meals (name, calories) 
VALUES ($1, $2) 
RETURNING id, name, calories, created_at
`

type CreateDailyMealParams struct {
	Name     string
	Calories int32
}

func (q *Queries) CreateDailyMeal(ctx context.Context, arg CreateDailyMealParams) (Meal, error) {
	row := q.db.QueryRow(ctx, createDailyMeal, arg.Name, arg.Calories)
	var i Meal
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Calories,
		&i.CreatedAt,
	)
	return i, err
}

const getDailyMeal = `-- name: GetDailyMeal :one
SELECT id, name, calories, created_at FROM meals
WHERE id = $1
`

func (q *Queries) GetDailyMeal(ctx context.Context, id int64) (Meal, error) {
	row := q.db.QueryRow(ctx, getDailyMeal, id)
	var i Meal
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Calories,
		&i.CreatedAt,
	)
	return i, err
}

const listDailyMeals = `-- name: ListDailyMeals :many
SELECT id, name, calories, created_at FROM meals
ORDER BY created_at DESC
`

func (q *Queries) ListDailyMeals(ctx context.Context) ([]Meal, error) {
	rows, err := q.db.Query(ctx, listDailyMeals)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Meal
	for rows.Next() {
		var i Meal
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Calories,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
