// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Meal struct {
	ID        int64
	Name      string
	Calories  int32
	CreatedAt pgtype.Timestamptz
}

type Stat struct {
	StatDate      pgtype.Date
	TotalCalories int32
	TotalMeals    int32
	UpdatedAt     pgtype.Timestamptz
}
