// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stats.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const upsertDailyStat = `-- name: UpsertDailyStat :one

INSERT INTO stats (stat_date, total_calories, total_meals)
VALUES ($1, $2, 1)
ON CONFLICT (stat_date) DO UPDATE SET 
    total_calories = stats.total_calories + EXCLUDED.total_calories, 
    total_meals = stats.total_meals + EXCLUDED.total_meals,
    updated_at = now()
RETURNING stat_date, total_calories, total_meals, updated_at
`

type UpsertDailyStatParams struct {
	StatDate      pgtype.Date
	TotalCalories int32
}

func (q *Queries) UpsertDailyStat(ctx context.Context, arg UpsertDailyStatParams) (Stat, error) {
	row := q.db.QueryRow(ctx, upsertDailyStat, arg.StatDate, arg.TotalCalories)
	var i Stat
	err := row.Scan(
		&i.StatDate,
		&i.TotalCalories,
		&i.TotalMeals,
		&i.UpdatedAt,
	)
	return i, err
}
